name: ci

on:
  push:
    branches: 
        - master
        - gh-actions

  pull_request:
    branches: 
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make test-gen2