name: ci

on:
  push:
    branches: 
        - master
        - gh-actions

  pull_request:
    branches: 
        - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gen1
      run: make test-gen1
    - name: gen2
      run: make test-gen2
    - name: gen3
      run: make test-gen3
  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build-gen1
      run: powershell .\build-win.ps1
    - name: test-gen1
      run: powershell .\test-win.ps1
